cmake_minimum_required(VERSION 3.16)
if(DEFINED ENV{IDF_PATH})
  include($ENV{IDF_PATH}/tools/cmake/project.cmake)
  project(biosecure)
else()
  project(biosecure_host LANGUAGES CXX)
  set(CMAKE_CXX_STANDARD 17)
  enable_testing()
  add_subdirectory(components/r307)
  add_subdirectory(components/core)
  add_subdirectory(simulator)
  add_subdirectory(tests)
endif()
